/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "std_types.h"

u32 SVC_execute();
void SVC_Handeler_C( u32 *a_MSP_value );


int main(void)
{
	/* Loop forever */
	u32 x = SVC_execute();

	for(;;);
}



u32 SVC_execute(void)
{
	u32 data;
	__asm volatile("SVC #5");
	__asm volatile("MOV %0,R0 " :"=r"(data) );
	return data;
}


__attribute__ ((naked)) void SVC_Handler(void) /* Make function naked to avoid the first instructions that uses the stack at the begining of function */
{
	/* MRS is an instruction to read special register */
	__asm volatile("MRS R0 , MSP" ); /* Get MSP value and put it in R0 as an argument */

	__asm volatile("B SVC_Handeler_C"); /* Branch to void SVC_Handeler_C function */
}


void SVC_Handeler_C( u32 *a_MSP_value )
{
	/* a_MSP_value    ==> address of place that contains (R0,PC,...)
	 * (*a_MSP_value) ==> Register value (R0,PC,...)
	 **/
	a_MSP_value += 6; /* ADD 6 steps to point to the address of PC */
	u16 *PC_value = *a_MSP_value; /* Get PC value */
	PC_value -= 1; /* Get the previous address in PC that is SVC instruction*/
	u8 SVC_value = *PC_value; /* Get SVC value */

	switch(SVC_value)
	{
	case 0:

		break;
	case 5:
        /* I want to return a value to the task */
		/* I will save the return value in R0 that is place in stack */
		a_MSP_value -= 6; /* The stack will point to R0 */
		(*a_MSP_value) = SVC_value*2 ;/* Put the value that you want to return (10)  */

		break;

	}

}

